// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreFoundation/CoreFoundation.h>
#import <CFNetwork/CFNetwork.h>
#import <CoreAudio/CoreAudio.h>
#import <MobileCoreServices/MobileCoreServices.h>
#import <Security/Security.h>
#import <SystemConfiguration/SystemConfiguration.h>
#import <SafariServices/SafariServices.h>

@interface String: NSObject
@end

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface GiveMeFiveViewController: UIViewController
-(IBAction) loadView;
-(IBAction) viewDidLoad;
-(IBAction) viewDidAppear:(id) animated;

@end

@interface GiveMeFiveLayout: MotionKit::Layout
-(IBAction) layout;
-(IBAction) action_button_style;
-(IBAction) collection_style;
-(IBAction) set_data;
-(IBAction) numberOfSectionsInCollectionView:(id) collectionView;
-(IBAction) initWithFrame:(id) frame;

@end

@interface GiveMeFiveCollectionCell: UICollectionViewCell
-(IBAction) initWithFrame:(id) frame;
-(IBAction) layout;
-(IBAction) cell_style;
-(IBAction) score_info_label_style;
-(IBAction) by_info_label_style;
-(IBAction) time_info_label_style;
-(IBAction) title_label_style;
-(IBAction) view_button_style;
-(IBAction) view_button_clicked;

@end

@interface GiveMeFiveCollectionCellLayout: MK::Layout
-(IBAction) layout;
-(IBAction) cell_style;
-(IBAction) score_info_label_style;
-(IBAction) by_info_label_style;
-(IBAction) time_info_label_style;
-(IBAction) title_label_style;
-(IBAction) view_button_style;
-(IBAction) view_button_clicked;

@end

@interface MiuViewController: UIViewController
-(IBAction) loadView;
-(IBAction) viewDidLoad;
-(IBAction) readom_sample;
-(IBAction) safariViewControllerDidFinish:(id) controller;

@end

@interface MiuLayout: MotionKit::Layout
-(IBAction) layout;
-(IBAction) action_button_style;
-(IBAction) action_label_style;

@end

@interface Readom: NSObject
@end

@interface StoriesViewController: UIViewController
-(IBAction) loadView;
-(IBAction) viewDidLoad;
-(IBAction) viewDidAppear:(id) animated;

@end

@interface StoriesLayout: MotionKit::Layout
-(IBAction) layout;
-(IBAction) title_label_style;
-(IBAction) table_style;

@end

