// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation String
@end

@implementation AppDelegate
@end

@implementation GiveMeFiveViewController
@end

@implementation GiveMeFiveLayout
@end

@implementation GiveMeFiveCollectionCell
@end

@implementation GiveMeFiveCollectionCellLayout
@end

@implementation MiuViewController
@end

@implementation MiuLayout
@end

@implementation Readom
@end

@implementation StoriesViewController
@end

@implementation StoriesLayout
@end

